/** Purpose: Define SOSync design tokens for NativeWind utility classes. */
module.exports = {
  presets: [require("nativewind/preset")],
  darkMode: "class",
  content: ["./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        canvas: "rgb(var(--bg-app) / <alpha-value>)",
        page: "rgb(var(--bg-app) / <alpha-value>)",
        secondaryPage: "rgb(var(--bg-secondary) / <alpha-value>)",
        surface: "rgb(var(--surface) / <alpha-value>)",
        panel: "rgb(var(--surface-elevated) / <alpha-value>)",
        input: "rgb(var(--surface-input) / <alpha-value>)",
        ink: "rgb(var(--text-primary) / <alpha-value>)",
        secondary: "rgb(var(--text-secondary) / <alpha-value>)",
        muted: "rgb(var(--text-muted) / <alpha-value>)",
        line: "rgb(var(--border-subtle) / <alpha-value>)",
        borderStrong: "rgb(var(--border-strong) / <alpha-value>)",
        primary: "rgb(var(--accent-primary) / <alpha-value>)",
        accent: "rgb(var(--accent-primary) / <alpha-value>)",
        profileAccent: "rgb(var(--accent-primary) / <alpha-value>)",
        profileAccentSoft: "rgb(var(--accent-soft) / <alpha-value>)",
        accentPressed: "rgb(var(--accent-pressed) / <alpha-value>)",
        accentOutline: "rgb(var(--accent-outline) / <alpha-value>)",
        caution: "rgb(var(--warning) / <alpha-value>)",
        warningSurface: "rgb(var(--warning-surface) / <alpha-value>)",
        warningBorder: "rgb(var(--warning-border) / <alpha-value>)",
        warningText: "rgb(var(--warning-text) / <alpha-value>)",
        danger: "rgb(var(--danger) / <alpha-value>)",
        dangerSurface: "rgb(var(--danger-surface) / <alpha-value>)",
        dangerBorder: "rgb(var(--danger-border) / <alpha-value>)",
        dangerText: "rgb(var(--danger-text) / <alpha-value>)",
        success: "rgb(var(--success) / <alpha-value>)",
        successSurface: "rgb(var(--success-surface) / <alpha-value>)",
        successBorder: "rgb(var(--success-border) / <alpha-value>)",
        successText: "rgb(var(--success-text) / <alpha-value>)",
        info: "rgb(var(--info) / <alpha-value>)",
        infoSurface: "rgb(var(--info-surface) / <alpha-value>)",
        infoBorder: "rgb(var(--info-border) / <alpha-value>)",
        infoText: "rgb(var(--info-text) / <alpha-value>)",
        focus: "rgb(var(--accent-pressed) / <alpha-value>)",
        soft: "rgb(var(--accent-soft) / <alpha-value>)",
        softText: "rgb(var(--text-primary) / <alpha-value>)",
      },
      boxShadow: {
        soft: "0 18px 36px rgba(20, 24, 32, 0.22)",
      },
      borderRadius: {
        card: "24px",
      },
    },
  },
  plugins: [],
};
